version: '3.9'
services:
  db:
    image: postgres:16.2
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    environment:
      POSTGRES_PASSWORD: postgres123
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: no
    ports:
      - 5433:8080
