# Use root/example as user/password credentials
services:

  mongo:
    image: mongo
    restart: no
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: notification123

  mongo-express:
    image: mongo-express
    restart: no
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: notification123
      ME_CONFIG_MONGODB_URL: mongodb://root:notification123@mongo:27017/
      ME_CONFIG_BASICAUTH: false