apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'notification-api-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['notification-api-service:8080']
      - job_name: 'user-api-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['user-api-service:8081']
      - job_name: 'schedule-api-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['schedule-api-service:8082']
      - job_name: 'notification-api-gateway-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['notification-api-gateway-service:9000']
