version: '3.9'
services:
  notification-api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    image: notification-api-gateway:latest
    container_name: notification-api-gateway
    ports:
      - "9000:9000"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    extra_hosts:
      - "host.docker.internal:host-gateway"
