apiVersion: v1
kind: Service
metadata:
  name: notification-api-gateway-service
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30000
  selector:
    app: notification-api-gateway
