services:
  schedule-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: schedule-api:latest
    container_name: schedule-api
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    extra_hosts:
      - "host.docker.internal:host-gateway"
