services:
  notification-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: notification-api:latest
    container_name: notification-api
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    extra_hosts:
      - "host.docker.internal:host-gateway"
