apiVersion: v1
kind: Service
metadata:
  name: notification-api-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
  selector:
    app: notification-api
